services:
  postgres:
    image: postgres
    env_file: katapult.env
    ports:
      - "9025:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    env_file: katapult.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
