# Generated by Django 4.1.7 on 2023-02-28 14:50

import uuid

import django.db.models.deletion
from django.db import migrations, models

import applications.provider.models.provider


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications_banks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name_provider", models.CharField(max_length=255)),
                (
                    "nit_provider",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[applications.provider.models.provider.validate_nit],
                    ),
                ),
                ("name_contact_person", models.CharField(max_length=255)),
                (
                    "number_contact_person",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("number_account_banking", models.CharField(blank=True, max_length=15)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banks_provider_related",
                        to="applications_banks.banks",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
    ]
